"""Updated user and resource models

Revision ID: 05754c8794a5
Revises: ccaadef4f0d8
Create Date: 2025-02-24 14:39:07.949102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05754c8794a5'
down_revision = 'ccaadef4f0d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_by', sa.Integer(), nullable=True))
        # Provide a name for the foreign key constraint
        batch_op.create_foreign_key(
            'fk_resources_user',  # Explicit name for the foreign key constraint
            'user',              # Referenced table
            ['submitted_by'],    # Local column(s)
            ['id']               # Referenced column(s)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        # Provide the same name for dropping the foreign key constraint
        batch_op.drop_constraint('fk_resources_user', type_='foreignkey')
        batch_op.drop_column('submitted_by')
    # ### end Alembic commands ###