"""Add support for external bookmarks

Revision ID: ccaadef4f0d8
Revises: 1c78875adf49
Create Date: 2025-02-23 20:30:31.551193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccaadef4f0d8'
down_revision = '1c78875adf49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=512), nullable=False))
        batch_op.add_column(sa.Column('source', sa.String(length=64), nullable=False))
        batch_op.alter_column('resource_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.alter_column('resource_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('source')
        batch_op.drop_column('url')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
